docker compose api and mongo and env example

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,10 +6,10 @@ merge-check:
   only:
     - merge_requests
   script:
-      - if [ "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}" == "main" && "${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}" =! "develop" ]; then
-          echo "Cannot merge to main branch directly. Please create a merge request from develop branch.";
-          exit 1;
-        else
-          echo "Cannot merge to main branch directly. Please create a merge request from develop branch.";
-          return 0;
-        fi
+    - if [ "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}" == "main" && "${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}" =! "develop" ]; then
+      echo "Cannot merge to main branch directly. Please create a merge request from develop branch.";
+        exit 1;
+      else
+        echo "Cannot merge to main branch directly. Please create a merge request from develop branch.";
+        return 0;
+      fi
