add merge check in gitlab ci yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -8,8 +8,8 @@ merge-check:
     - merge_requests
   script:
     - if [ "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}" == "main" ] && [ "${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}" != "develop" ]; then
-        echo "Cannot merge to the main branch directly. Please create a merge request from the develop branch."
-        exit 1
+        echo "Cannot merge to the main branch directly. Please create a merge request from the develop branch.";
+        exit 1;
       else
-        exit 0
+        exit 0;
       fi
